/*
 * Copyright 2010-2011 Pierre-Yves Ricau (py.ricau at gmail.com)
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package com.googlecode.androidannotations.generation;

import java.io.IOException;
import java.io.Writer;

import com.googlecode.androidannotations.model.Instruction;
import com.googlecode.androidannotations.model.MetaActivity;

public class ActivityGenerator {

	private static final String CLASS_FORMAT = //
	"" + //
			"/* DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations. */\n" + //
			"package %s;\n" + //
			"\n" + //
			"public class %s extends %s %s{\n" + //
			"\n" + //
			"    @Override\n" + //
			"    public void onCreate(android.os.Bundle savedInstanceState) {\n" + //
			"\n" + //
			"%s" + //
			"        setContentView(%s);\n" + //
			"\n" + //
			"%s" + //
			"        super.onCreate(savedInstanceState);\n" + //
			"    }\n" + //
			"\n" + //
			"%s" + //
			"}\n";

	public void generate(MetaActivity activity, Writer writer) throws IOException {
		StringBuilder onCreateInstructionsBuilder = new StringBuilder();
		for (Instruction instruction : activity.getOnCreateInstructions()) {
			onCreateInstructionsBuilder.append(instruction.generate());
		}
		
		StringBuilder beforeCreateInstructionsBuilder = new StringBuilder();
		for (Instruction instruction : activity.getBeforeCreateInstructions()) {
			beforeCreateInstructionsBuilder.append(instruction.generate());
		}

		StringBuilder memberInstructionsBuilder = new StringBuilder();
		for (Instruction instruction : activity.getMemberInstructions()) {
			memberInstructionsBuilder.append(instruction.generate());
		}

		StringBuilder implementsBuilder = new StringBuilder();
		boolean first = true;
		for (String implementedInterface : activity.getImplementedInterfaces()) {
			if (first) {
				implementsBuilder.append("implements ");
				first = false;
			} else {
				implementsBuilder.append(", ");
			}
			implementsBuilder.append(implementedInterface);
		}

		String generatedClass = String.format(CLASS_FORMAT, //
				activity.getPackageName(), //
				activity.getClassSimpleName(), //
				activity.getSuperClassName(), //
				implementsBuilder.toString(), //
				beforeCreateInstructionsBuilder.toString(), //
				activity.getLayoutQualifiedName(), //
				onCreateInstructionsBuilder.toString(), //
				memberInstructionsBuilder.toString());

		writer.append(generatedClass);

	}

}
