/*
 * Copyright 2010-2011 Pierre-Yves Ricau (py.ricau at gmail.com)
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package com.googlecode.androidannotations.generation;

import java.io.IOException;
import java.io.Writer;
import java.util.Set;

import com.googlecode.androidannotations.model.Instruction;
import com.googlecode.androidannotations.model.MetaActivity;

public class ActivityGenerator {
	
	private static final String IMPORT_FORMAT = "import %s;\n";
	private static final String STATIC_IMPORT_FORMAT = "import static %s;\n";

	private static final String CLASS_FORMAT = //
	"" + //
			"/* DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations. */\n" + //
			"package %s;\n" + //
			"\n" + //
			"%s" + //
			"\n" + //
			"public class %s extends %s %s{\n" + //
			"\n" + //
			"    @Override\n" + //
			"    public void onCreate(Bundle savedInstanceState) {\n" + //
			"\n" + //
			"%s" + //
			"        %s\n" + //
			"\n" + //
			"%s" + //
			"        super.onCreate(savedInstanceState);\n" + //
			"    }\n" + //
			"\n" + //
			"%s" + //
			"}\n";

	public void generate(MetaActivity activity, Writer writer) throws IOException {
		
		Set<String> imports = activity.getImports();
		Set<String> staticImports = activity.getStaticImports();
		
		imports.add("android.os.Bundle");
		
		StringBuilder importBuilder = new StringBuilder();
		for(String activityImport : imports) {
			importBuilder.append(String.format(IMPORT_FORMAT, activityImport));
		}
		for(String activityStaticImport : staticImports) {
			importBuilder.append(String.format(STATIC_IMPORT_FORMAT, activityStaticImport));
		}
		

		StringBuilder onCreateInstructionsBuilder = new StringBuilder();
		for (Instruction instruction : activity.getOnCreateInstructions()) {
			onCreateInstructionsBuilder.append(instruction.generate());
		}

		StringBuilder beforeCreateInstructionsBuilder = new StringBuilder();
		for (Instruction instruction : activity.getBeforeCreateInstructions()) {
			beforeCreateInstructionsBuilder.append(instruction.generate());
		}

		StringBuilder memberInstructionsBuilder = new StringBuilder();
		for (Instruction instruction : activity.getMemberInstructions()) {
			memberInstructionsBuilder.append(instruction.generate());
		}

		StringBuilder implementsBuilder = new StringBuilder();
		boolean first = true;
		for (String implementedInterface : activity.getImplementedInterfaces()) {
			if (first) {
				implementsBuilder.append("implements ");
				first = false;
			} else {
				implementsBuilder.append(", ");
			}
			implementsBuilder.append(implementedInterface);
		}

		String layoutQualifiedName = activity.getLayoutQualifiedName();
		String setContentView = layoutQualifiedName != null ? "setContentView(" + layoutQualifiedName + ");" : "";

		String generatedClass = String.format(CLASS_FORMAT, //
				activity.getPackageName(), //
				importBuilder.toString(), //
				activity.getClassSimpleName(), //
				activity.getSuperClassName(), //
				implementsBuilder.toString(), //
				beforeCreateInstructionsBuilder.toString(), //
				setContentView, //
				onCreateInstructionsBuilder.toString(), //
				memberInstructionsBuilder.toString());

		writer.append(generatedClass);
	}
}
